### ISSUE TITLE
Update for DF?

### ISSUE THREAD

**Issue by Maverick-PDS** [collinstevens/nameplateBuffs#1]
Hi Collin! I was wondering if you're going to join us for DF?

The addon worked in the pre-patch, but as of today icons don't show up on enemy nameplates anymore (although the addon seems to load fine). I think it's just something to do with the vers. number.

**Comment by collinstevens** [comment]
@Maverick-PDS I don't use this anymore, but I'll give it a try this weekend. If there are breaking changes in the WoW API, I may just deprecate the addon unfortunately.

**Comment by Maverick-PDS** [comment]
@collinstevens thanks so much! I hope it's just an update of the ToS/Version Number, something like that.

May I ask what you use instead? If it's not easily fixable, I'd like to try your replacement.

And thanks so much for making it in the first place, helped me all of Shadowlands. Easy to config, works with many nameplates, great all around!

**Comment by collinstevens** [comment]
> @collinstevens thanks so much! I hope it's just an update of the ToS/Version Number, something like that.

Unfortunately it wasn't just this. @shamilla helped out a bunch with a couple PRs. I updated the dependencies and the version numbers. I just published a release to CurseForge.

> May I ask what you use instead? If it's not easily fixable, I'd like to try your replacement.

I use Plater nowadays.

**Comment by Maverick-PDS** [comment]
@collinstevens @shamilla Thank you so, so much! I just love KUI Nameplates + Nameplatebuffs for Auras. Really do appreciate it!
